// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Link from "next/link";
import Footer from "@/components/footer";
import NavbarLayout from "./navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <nav> */}
        {/* <Link href='/' style={{marginRight: 10}}>Home</Link>
          <Link href='./ContactUs' style={{marginRight: 10}}>Contact</Link>
          <Link href='./Faq' style={{marginRight: 10}}>Faq</Link>
          <Link href='./Vendors' style={{marginRight: 10}}>Vendors</Link>
          <Link href='./Sell' style={{marginRight: 10}}>Sell</Link>
          <Link href='./Voucher' style={{marginRight: 10}}>Voucher</Link>
          <Link href='./VirtualCard' style={{marginRight: 10}}>VCard</Link>
          <Link href='./Terms' style={{marginRight: 10}}>Terms</Link> */}
       <NavbarLayout />
        {/* </nav> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
